import { Injectable } from '@angular/core';

import { SupportedLanguage } from '../models/supported-language.model'

const supportedLanguages: SupportedLanguage[] = [
  { languageCode: 'na', displayNameEN: 'Turn off', displayNameTH: 'ปิด', displayNameJA: '消す', displayNameZH: '關閉', displayNameIT: 'Spegnere', displayNameES: 'apagar', displayNameKO: '끄다', displayNameID: 'Mematikan', displayNameVI: 'tắt', displayNameDE: 'Ausschalten', displayNamePT: 'Desligar', displayNameFR: 'Éteindre', displayNameTR: 'Kapatmak', displayNameRU: 'TRUN OFF', nativeName: '-', sortOrder: 7 },
  { languageCode: 'en', displayNameEN: 'English', displayNameTH: 'อังกฤษ', displayNameJA: '英語', displayNameZH: '英语', displayNameIT: 'Inglese', displayNameES: 'inglés', displayNameKO: '영어', displayNameID: 'Inggris', displayNameVI: 'Anh', displayNameDE: 'Englisch', displayNamePT: 'Inglês', displayNameFR: 'Anglais', displayNameTR: 'İngilizce', displayNameRU: 'английский', nativeName: 'English', sortOrder: 5 },
  { languageCode: 'ja', displayNameEN: 'Japanese', displayNameTH: 'ญี่ปุ่น', displayNameJA: '日本語', displayNameZH: '日语', displayNameIT: 'Giapponese', displayNameES: 'japonés', displayNameKO: '일본어', displayNameID: 'Jepang', displayNameVI: 'Nhật', displayNameDE: 'Japanisch', displayNamePT: 'Japonês', displayNameFR: 'Japonais', displayNameTR: 'Japonca', displayNameRU: 'японский', nativeName: '日本語', sortOrder: 4 },
  { languageCode: 'th', displayNameEN: 'Thai', displayNameTH: 'ไทย', displayNameJA: 'タイ語', displayNameZH: '泰语', displayNameIT: 'Tailandese', displayNameES: 'tailandés', displayNameKO: '태국어', displayNameID: 'Thai', displayNameVI: 'Thái', displayNameDE: 'Thailändisch', displayNamePT: 'Tailandês', displayNameFR: 'Thaï', displayNameTR: 'Tay Dili', displayNameRU: 'тайский', nativeName: 'ไทย', sortOrder: 3 },
  { languageCode: 'id', displayNameEN: 'Indonesian', displayNameTH: 'อินโดนีเซีย', displayNameJA: 'インドネシア語', displayNameZH: '印尼语', displayNameIT: 'Indonesiano', displayNameES: 'indonesio', displayNameKO: '인도네시아어', displayNameID: 'Indonesia', displayNameVI: 'Indonesia', displayNameDE: 'Indonesisch', displayNamePT: 'Indonésio', displayNameFR: 'Indonésien', displayNameTR: 'Endonezya Dili', displayNameRU: 'индонезийский', nativeName: 'Indonesia', sortOrder: 2 },
  { languageCode: 'zh-CN', displayNameEN: 'Chinese(Simp.)', displayNameTH: 'จีน (ตัวย่อ)', displayNameJA: '中国語(簡体)', displayNameZH: '中文(简体)', displayNameIT: 'Cinese(semp.)', displayNameES: 'chino (simp.)', displayNameKO: '중국어(간체)', displayNameID: 'China (Sede.)', displayNameVI: 'Trung(Giản)', displayNameDE: 'Chinesisch(vere.)', displayNamePT: 'Chinês simp.', displayNameFR: 'Chinois(simp.)', displayNameTR: 'Çince(Basi.)', displayNameRU: 'китайский(упро.)', nativeName: '汉语', sortOrder: 1 },
  { languageCode: 'jw', displayNameEN: 'Javanese', displayNameTH: 'ชวา', displayNameJA: 'ジャワ語', displayNameZH: '印尼爪哇语', displayNameIT: 'Giavanese', displayNameES: 'javanés', displayNameKO: '자바어', displayNameID: 'Jawa', displayNameVI: 'Java', displayNameDE: 'Javanisch', displayNamePT: 'Javanês', displayNameFR: 'Javanais', displayNameTR: 'Cava Dili', displayNameRU: 'яванский', nativeName: 'Basa Jawa', },
  { languageCode: 'su', displayNameEN: 'Sundanese', displayNameTH: 'ซุนดา', displayNameJA: 'スンダ語', displayNameZH: '印尼巽他语', displayNameIT: 'Sundanese', displayNameES: 'sundanés', displayNameKO: '순다어', displayNameID: 'Sunda', displayNameVI: 'Sunda', displayNameDE: 'Sundanesisch', displayNamePT: 'Sudanês', displayNameFR: 'Soundanais', displayNameTR: 'Sundanizce', displayNameRU: 'суданский', nativeName: 'Basa Sunda' },
  { languageCode: 'ms', displayNameEN: 'Malay', displayNameTH: 'มาเลย์', displayNameJA: 'マレー語', displayNameZH: '馬來語', displayNameIT: 'Malese', displayNameES: 'malayo', displayNameKO: '말레이어', displayNameID: 'Melayu', displayNameVI: 'Mã Lai', displayNameDE: 'Malaysisch', displayNamePT: 'Malaio', displayNameFR: 'Malaisien', displayNameTR: 'Malezya Dili', displayNameRU: 'малайский', nativeName: 'Bahasa melayu' },
  { languageCode: 'vi', displayNameEN: 'Vietnamese', displayNameTH: 'เวียดนาม', displayNameJA: 'ベトナム語', displayNameZH: '马来语', displayNameIT: 'Vietnamita', displayNameES: 'vietnamita', displayNameKO: '베트남어', displayNameID: 'Vietnam', displayNameVI: 'Việt', displayNameDE: 'Vietnamesisch', displayNamePT: 'Vietnamita', displayNameFR: 'Vietnamien', displayNameTR: 'Vietnamca', displayNameRU: 'вьетнамский', nativeName: 'Tiếng Việt' },
  { languageCode: 'af', displayNameEN: 'Afrikaans', displayNameTH: 'แอฟริกา', displayNameJA: 'アフリカーンス語', displayNameZH: '布尔语(南非荷兰语)', displayNameIT: 'Afrikaans', displayNameES: 'afrikáans', displayNameKO: '아프리칸스어', displayNameID: 'Afrikans', displayNameVI: 'Hà Lan (Nam Phi)', displayNameDE: 'Afrikaans', displayNamePT: 'Afrikaans', displayNameFR: 'Afrikaans', displayNameTR: 'Afrika Dili', displayNameRU: 'африкаанс', nativeName: 'Afrikaans' },
  { languageCode: 'sq', displayNameEN: 'Albanian', displayNameTH: 'แอลเบเนีย', displayNameJA: 'アルバニア語', displayNameZH: '阿尔巴尼亚语', displayNameIT: 'Albanese', displayNameES: 'albanés', displayNameKO: '알바니아어', displayNameID: 'Albania', displayNameVI: 'Albania', displayNameDE: 'Albanisch', displayNamePT: 'Albanês', displayNameFR: 'Albanais', displayNameTR: 'Arnavutça', displayNameRU: 'албанский', nativeName: 'shqip / gjuha shqipe' },
  { languageCode: 'am', displayNameEN: 'Amharic', displayNameTH: 'อัมฮาริก', displayNameJA: 'アムハラ語', displayNameZH: '阿姆哈拉语', displayNameIT: 'Amarico', displayNameES: 'amhárico', displayNameKO: '암하라어', displayNameID: 'Amhara', displayNameVI: 'Amharic', displayNameDE: 'Amharisch', displayNamePT: 'Amárico', displayNameFR: 'Amharique', displayNameTR: 'Habeşçe', displayNameRU: 'амхарский', nativeName: 'ኣማርኛ' },
  { languageCode: 'ar', displayNameEN: 'Arabic', displayNameTH: 'อาหรับ', displayNameJA: 'アラビア語', displayNameZH: '阿拉伯语', displayNameIT: 'Arabo', displayNameES: 'árabe', displayNameKO: '아랍어', displayNameID: 'Arab', displayNameVI: 'Ả Rập', displayNameDE: 'Arabisch', displayNamePT: 'árabe', displayNameFR: 'Arabe', displayNameTR: 'Arapça', displayNameRU: 'арабский', nativeName: 'العربية' },
  { languageCode: 'hy', displayNameEN: 'Armenian', displayNameTH: 'อาร์เมเนีย', displayNameJA: 'アルメニア語', displayNameZH: '亚美尼亚语', displayNameIT: 'Armeno', displayNameES: 'armenio', displayNameKO: '아르메니아어', displayNameID: 'Armenia', displayNameVI: 'Armenia', displayNameDE: 'Armenisch', displayNamePT: 'Armênio', displayNameFR: 'Arménien', displayNameTR: 'Ermenice', displayNameRU: 'армянский', nativeName: 'Հայերէն' },
  { languageCode: 'az', displayNameEN: 'Azerbaijani', displayNameTH: 'อาร์เซอร์ไบจัน', displayNameJA: 'アゼルバイジャン語', displayNameZH: '阿塞拜疆语', displayNameIT: 'Azero', displayNameES: 'azerí', displayNameKO: '아제르바이잔어', displayNameID: 'Azerbaijan', displayNameVI: 'Azerbaijan', displayNameDE: 'Aserbaidschanisch', displayNamePT: 'Azerbaijani', displayNameFR: 'Azéri', displayNameTR: 'Azerice', displayNameRU: 'азербайджанский', nativeName: 'Азәрбајҹан дили' },
  { languageCode: 'eu', displayNameEN: 'Basque', displayNameTH: 'บาสก์', displayNameJA: 'バスク語', displayNameZH: '巴斯克语', displayNameIT: 'Basco', displayNameES: 'euskera', displayNameKO: '바스크어', displayNameID: 'Basque', displayNameVI: 'Basque', displayNameDE: 'Baskisch', displayNamePT: 'Basca', displayNameFR: 'Basque', displayNameTR: 'Baskça', displayNameRU: 'баскский', nativeName: 'euskara' },
  { languageCode: 'be', displayNameEN: 'Belarusian', displayNameTH: 'เบลารุส', displayNameJA: 'ベラルーシ語', displayNameZH: '白俄罗斯语', displayNameIT: 'Bielorusso', displayNameES: 'bielorruso', displayNameKO: '벨라루스어', displayNameID: 'Belarussia', displayNameVI: 'Belarus', displayNameDE: 'Weißrussisch', displayNamePT: 'Bielorusso', displayNameFR: 'Biélorusse', displayNameTR: 'Belarusça', displayNameRU: 'белорусский', nativeName: 'Беларуская мова' },
  { languageCode: 'bn', displayNameEN: 'Bengali', displayNameTH: 'เบงกอล', displayNameJA: 'ベンガル語', displayNameZH: '孟加拉语', displayNameIT: 'Bengalese', displayNameES: 'bengalí', displayNameKO: '벵골어', displayNameID: 'Bengali', displayNameVI: 'Bengal', displayNameDE: 'Bengalisch', displayNamePT: 'Bengali', displayNameFR: 'Bengali', displayNameTR: 'Bengalce', displayNameRU: 'бенгальский', nativeName: 'বাংলা' },
  { languageCode: 'bs', displayNameEN: 'Bosnian', displayNameTH: 'บอสเนีย', displayNameJA: 'ボスニア語', displayNameZH: '波斯尼亚语', displayNameIT: 'Bosniaco', displayNameES: 'bosnio', displayNameKO: '보스니아어', displayNameID: 'Bosnia', displayNameVI: 'Bosnia', displayNameDE: 'Bosnisch', displayNamePT: 'Bósnio', displayNameFR: 'Bosniaque', displayNameTR: 'Boşnakça', displayNameRU: 'боснийский', nativeName: 'босански' },
  { languageCode: 'bg', displayNameEN: 'Bulgarian', displayNameTH: 'บัลแกเรีย', displayNameJA: 'ブルガリア語', displayNameZH: '保加利亚语', displayNameIT: 'Bulgaro', displayNameES: 'búlgaro', displayNameKO: '불가리아어', displayNameID: 'Bulgaria', displayNameVI: 'Bulgaria', displayNameDE: 'Bulgarisch', displayNamePT: 'Búlgaro', displayNameFR: 'Bulgare', displayNameTR: 'Bulgarca', displayNameRU: 'болгарский', nativeName: 'български език' },
  { languageCode: 'ca', displayNameEN: 'Catalan', displayNameTH: 'คาตาลัน', displayNameJA: 'カタルーニャ語', displayNameZH: '加泰罗尼亚语', displayNameIT: 'Catalano', displayNameES: 'catalán', displayNameKO: '카탈로니아어', displayNameID: 'Katala', displayNameVI: 'Catalan', displayNameDE: 'Katalanisch', displayNamePT: 'Catalão', displayNameFR: 'Catalan', displayNameTR: 'Katalanca', displayNameRU: 'каталанский', nativeName: 'català' },
  { languageCode: 'ceb', displayNameEN: 'Cebuano', displayNameTH: 'ซีบัวโน', displayNameJA: 'セブアノ語', displayNameZH: '宿务语', displayNameIT: 'Cebuano', displayNameES: 'cebuano', displayNameKO: '세부아노', displayNameID: 'Cebuano', displayNameVI: 'Cebuano', displayNameDE: 'Cebuano', displayNamePT: 'Cebuano', displayNameFR: 'Cebuano', displayNameTR: 'Cebuano', displayNameRU: 'себуанский', nativeName: 'Sinugboanon / Sugboanon' },
  { languageCode: 'ny', displayNameEN: 'Chichewa', displayNameTH: 'ชิเชวา', displayNameJA: 'チェワ語', displayNameZH: '齐切瓦语', displayNameIT: 'Chichewa', displayNameES: 'chichewa', displayNameKO: '체와어', displayNameID: 'Chichewa', displayNameVI: 'Chichewa', displayNameDE: 'Chichewa', displayNamePT: 'Chichewa', displayNameFR: 'Chichewa', displayNameTR: 'Chicheva', displayNameRU: 'чева', nativeName: 'Chicheŵa' },
  { languageCode: 'zh-TW', displayNameEN: 'Chinese(Trad.)', displayNameTH: 'จีน (ตัวเต็ม)', displayNameJA: '中国語(繁体)', displayNameZH: '中文(繁体)', displayNameIT: 'Cinese(trad.)', displayNameES: 'chino (trad.)', displayNameKO: '중국어(번체)', displayNameID: 'China (Trad.)', displayNameVI: 'Trung(Phồn)', displayNameDE: 'Chinesisch(trad.)', displayNamePT: 'Chinês trad.', displayNameFR: 'Chinois(trad.)', displayNameTR: 'Çince(Gele.)', displayNameRU: 'китайский(трад.)', nativeName: '漢語' },
  { languageCode: 'co', displayNameEN: 'Corsican', displayNameTH: 'คอร์สิกา', displayNameJA: 'コルシカ語', displayNameZH: '科西嘉语', displayNameIT: 'Corso', displayNameES: 'corso', displayNameKO: '코르시카어', displayNameID: 'Korsika', displayNameVI: 'Corsi', displayNameDE: 'Korsisch', displayNamePT: 'Corso', displayNameFR: 'Corse', displayNameTR: 'Korsika Dili', displayNameRU: 'корсиканский', nativeName: 'corsu' },
  { languageCode: 'hr', displayNameEN: 'Croatian', displayNameTH: 'โครเอเชีย', displayNameJA: 'クロアチア語', displayNameZH: '克罗地亚语', displayNameIT: 'Croato', displayNameES: 'croata', displayNameKO: '크로아티아어', displayNameID: 'Kroat', displayNameVI: 'Croatia', displayNameDE: 'Kroatisch', displayNamePT: 'Croata', displayNameFR: 'Croate', displayNameTR: 'Hırvatça', displayNameRU: 'хорватский', nativeName: 'Hrvatski' },
  { languageCode: 'cs', displayNameEN: 'Czech', displayNameTH: 'เช็ก', displayNameJA: 'チェコ語', displayNameZH: '捷克语', displayNameIT: 'Ceco', displayNameES: 'checo', displayNameKO: '체코어', displayNameID: 'Ceko', displayNameVI: 'Séc', displayNameDE: 'Tschechisch', displayNamePT: 'Tcheco', displayNameFR: 'Tchèque', displayNameTR: 'Çekçe', displayNameRU: 'чешский', nativeName: 'český jazyk' },
  { languageCode: 'da', displayNameEN: 'Danish', displayNameTH: 'เดนมาร์ก', displayNameJA: 'デンマーク語', displayNameZH: '丹麦语', displayNameIT: 'Danese', displayNameES: 'danés', displayNameKO: '덴마크어', displayNameID: 'Denmark', displayNameVI: 'Đan Mạch', displayNameDE: 'Dänisch', displayNamePT: 'Dinamarquês', displayNameFR: 'Danois', displayNameTR: 'Danca', displayNameRU: 'датский', nativeName: 'dansk' },
  { languageCode: 'nl', displayNameEN: 'Dutch', displayNameTH: 'ดัตช์', displayNameJA: 'オランダ語', displayNameZH: '荷兰语', displayNameIT: 'Olandese', displayNameES: 'neerlandés', displayNameKO: '네덜란드어', displayNameID: 'Belanda', displayNameVI: 'Hà Lan', displayNameDE: 'Niederländisch', displayNamePT: 'Holandês', displayNameFR: 'Néerlandais', displayNameTR: 'Felemenkçe', displayNameRU: 'нидерландский', nativeName: 'Nederlands' },
  { languageCode: 'eo', displayNameEN: 'Esperanto', displayNameTH: 'เอสเปอแรนโต', displayNameJA: 'エスペラント語', displayNameZH: '世界语', displayNameIT: 'Esperanto', displayNameES: 'esperanto', displayNameKO: '에스페란토어', displayNameID: 'Esperanto', displayNameVI: 'Quốc tế ngữ', displayNameDE: 'Esperanto', displayNamePT: 'Esperanto', displayNameFR: 'Espéranto', displayNameTR: 'Esperantoca', displayNameRU: 'эсперанто', nativeName: 'Esperanto' },
  { languageCode: 'et', displayNameEN: 'Estonian', displayNameTH: 'เอสโทเนีย', displayNameJA: 'エストニア語', displayNameZH: '爱沙尼亚语', displayNameIT: 'Estone', displayNameES: 'estonio', displayNameKO: '에스토니아어', displayNameID: 'Estonia', displayNameVI: 'Estonia', displayNameDE: 'Estnisch', displayNamePT: 'Estoniano', displayNameFR: 'Estonien', displayNameTR: 'Estonyaca', displayNameRU: 'эстонский', nativeName: 'eesti keel' },
  { languageCode: 'tl', displayNameEN: 'Filipino', displayNameTH: 'ฟิลิปปินส์', displayNameJA: 'タガログ語', displayNameZH: '菲律宾语', displayNameIT: 'Filippino', displayNameES: 'tagalo', displayNameKO: '타갈로그어', displayNameID: 'Tagalog', displayNameVI: 'Filipino', displayNameDE: 'Filipino', displayNamePT: 'Filipino', displayNameFR: 'Philippin', displayNameTR: 'Filipince', displayNameRU: 'филиппинский', nativeName: 'Tagalog' },
  { languageCode: 'fi', displayNameEN: 'Finnish', displayNameTH: 'ฟินแลนด์', displayNameJA: 'フィンランド語', displayNameZH: '芬兰语', displayNameIT: 'Finlandese', displayNameES: 'finlandés', displayNameKO: '핀란드어', displayNameID: 'Finlandia', displayNameVI: 'Phần Lan', displayNameDE: 'Finnisch', displayNamePT: 'Finlandês', displayNameFR: 'Finnois', displayNameTR: 'Fince', displayNameRU: 'финский', nativeName: 'suomi / suomen kieli' },
  { languageCode: 'fr', displayNameEN: 'French', displayNameTH: 'ฝรั่งเศส', displayNameJA: 'フランス語', displayNameZH: '法语', displayNameIT: 'Francese', displayNameES: 'francés', displayNameKO: '프랑스어', displayNameID: 'Prancis', displayNameVI: 'Pháp', displayNameDE: 'Französisch', displayNamePT: 'Francês', displayNameFR: 'Français', displayNameTR: 'Fransızca', displayNameRU: 'французский', nativeName: 'français' },
  { languageCode: 'fy', displayNameEN: 'Frisian', displayNameTH: 'ฟริเชียน', displayNameJA: 'フリジア語', displayNameZH: '弗里西语', displayNameIT: 'Frisone', displayNameES: 'frisio', displayNameKO: '프리지아어', displayNameID: 'Frisia', displayNameVI: 'Frisia', displayNameDE: 'Friesisch', displayNamePT: 'Frísio', displayNameFR: 'Frison', displayNameTR: 'Frizon Dili', displayNameRU: 'фризский', nativeName: 'Noordfreesk' },
  { languageCode: 'gl', displayNameEN: 'Galician', displayNameTH: 'กาลิเชียน', displayNameJA: 'ガリシア語', displayNameZH: '加利西亚语', displayNameIT: 'Galiziano', displayNameES: 'gallego', displayNameKO: '갈리시아어', displayNameID: 'Galisia', displayNameVI: 'Galicia', displayNameDE: 'Galizisch', displayNamePT: 'Galego', displayNameFR: 'Galicien', displayNameTR: 'Galiçyaca', displayNameRU: 'галисийский', nativeName: 'Galego' },
  { languageCode: 'ka', displayNameEN: 'Georgian', displayNameTH: 'จอร์เจีย', displayNameJA: 'ジョージア(グルジア)語', displayNameZH: '格鲁吉亚语', displayNameIT: 'Georgiano', displayNameES: 'georgiano', displayNameKO: '조지아어', displayNameID: 'Georgia', displayNameVI: 'George', displayNameDE: 'Georgisch', displayNamePT: 'Georgiano', displayNameFR: 'Géorgien', displayNameTR: 'Gürcüce', displayNameRU: 'грузинский', nativeName: 'ქართული ენა' },
  { languageCode: 'de', displayNameEN: 'German', displayNameTH: 'เยอรมัน', displayNameJA: 'ドイツ語', displayNameZH: '德语', displayNameIT: 'Tedesco', displayNameES: 'alemán', displayNameKO: '독일어', displayNameID: 'Jerman', displayNameVI: 'Đức', displayNameDE: 'Deutsch', displayNamePT: 'Alemão', displayNameFR: 'Allemand', displayNameTR: 'Almanca', displayNameRU: 'немецкий', nativeName: 'Deutsch' },
  { languageCode: 'el', displayNameEN: 'Greek', displayNameTH: 'คุชราต', displayNameJA: 'ギリシャ語', displayNameZH: '希腊语', displayNameIT: 'Greco', displayNameES: 'griego', displayNameKO: '그리스어', displayNameID: 'Yunani', displayNameVI: 'Hy Lạp', displayNameDE: 'Griechisch', displayNamePT: 'Grego', displayNameFR: 'Grec', displayNameTR: 'Yunanca', displayNameRU: 'греческий', nativeName: 'ελληνικά' },
  { languageCode: 'gu', displayNameEN: 'Gujarati', displayNameTH: 'คุชราต', displayNameJA: 'グジャラト語', displayNameZH: '古吉拉特语', displayNameIT: 'Gujarati', displayNameES: 'gujarati', displayNameKO: '구자라트어', displayNameID: 'Gujarati', displayNameVI: 'Gujarat', displayNameDE: 'Gujarati', displayNamePT: 'Guzerate', displayNameFR: 'Gujarati', displayNameTR: 'Gücerat Dili', displayNameRU: 'гуджарати', nativeName: 'ગુજરાતી' },
  { languageCode: 'ht', displayNameEN: 'Haitian Creole', displayNameTH: 'เฮติครีโอล', displayNameJA: 'ハイチ語', displayNameZH: '海地克里奥尔语', displayNameIT: 'Creolo haitiano', displayNameES: 'criollo haitiano', displayNameKO: '아이티 크리올어', displayNameID: 'Kreol Haiti', displayNameVI: 'Creole (Haiti)', displayNameDE: 'Haitianisch', displayNamePT: 'Crioulo haitiano', displayNameFR: 'Créole haïtien', displayNameTR: 'Haiti Creole Dili', displayNameRU: 'креольский (Гаити)', nativeName: 'Kreyòl ayisyen' },
  { languageCode: 'ha', displayNameEN: 'Hausa', displayNameTH: 'ฮัวซา', displayNameJA: 'ハウサ語', displayNameZH: '豪萨语', displayNameIT: 'Hausa', displayNameES: 'hausa', displayNameKO: '하우사어', displayNameID: 'Hausa', displayNameVI: 'Hausa', displayNameDE: 'Hausa', displayNamePT: 'Hausa', displayNameFR: 'Haoussa', displayNameTR: 'Hausa Dili', displayNameRU: 'хауса', nativeName: '(ḥawsa) حَوْسَ' },
  { languageCode: 'haw', displayNameEN: 'Hawaiian', displayNameTH: 'ฮาวาย', displayNameJA: 'ハワイ語', displayNameZH: '夏威夷语', displayNameIT: 'Hawaiano', displayNameES: 'hawaiano', displayNameKO: '하와이어', displayNameID: 'Hawaii', displayNameVI: 'Hawaii', displayNameDE: 'Hawaiisch', displayNamePT: 'Havaiano', displayNameFR: 'Hawaïen', displayNameTR: 'Havai Dili', displayNameRU: 'гавайский', nativeName: 'ʻōlelo Hawaiʻi' },
  { languageCode: 'iw', displayNameEN: 'Hebrew', displayNameTH: 'ฮีบรู', displayNameJA: 'ヘブライ語', displayNameZH: '希伯来语', displayNameIT: 'Ebraico', displayNameES: 'hebreo', displayNameKO: '히브리어', displayNameID: 'Ibrani', displayNameVI: 'Do Thái', displayNameDE: 'Hebräisch', displayNamePT: 'Hebraico', displayNameFR: 'Hébreu', displayNameTR: 'İbranice', displayNameRU: 'иврит', nativeName: 'עברית / עִבְרִית' },
  { languageCode: 'hi', displayNameEN: 'Hindi', displayNameTH: 'ฮินดี', displayNameJA: 'ヒンディー語', displayNameZH: '印地语', displayNameIT: 'Hindi', displayNameES: 'hindi', displayNameKO: '힌디어', displayNameID: 'Hindi', displayNameVI: 'Hindi', displayNameDE: 'Hindi', displayNamePT: 'Hindi', displayNameFR: 'Hindi', displayNameTR: 'Hintçe', displayNameRU: 'хинди', nativeName: 'हिन्दी' },
  { languageCode: 'hmn', displayNameEN: 'Hmong', displayNameTH: 'ม้ง', displayNameJA: 'モン語', displayNameZH: '苗语', displayNameIT: 'Hmong', displayNameES: 'hmong', displayNameKO: '몽어', displayNameID: 'Hmong', displayNameVI: 'Hmong', displayNameDE: 'Hmong', displayNamePT: 'Hmong', displayNameFR: 'Hmong', displayNameTR: 'Hmong Dili', displayNameRU: 'хмонг', nativeName: 'Hmong' },
  { languageCode: 'hu', displayNameEN: 'Hungarian', displayNameTH: 'ฮังการี', displayNameJA: 'ハンガリー語', displayNameZH: '匈牙利语', displayNameIT: 'Ungherese', displayNameES: 'húngaro', displayNameKO: '헝가리어', displayNameID: 'Magyar', displayNameVI: 'Hungary', displayNameDE: 'Ungarisch', displayNamePT: 'Húngaro', displayNameFR: 'Hongrois', displayNameTR: 'Macarca', displayNameRU: 'венгерский', nativeName: 'magyar nyelv' },
  { languageCode: 'is', displayNameEN: 'Icelandic', displayNameTH: 'ไอซ์แลนด์', displayNameJA: 'アイスランド語', displayNameZH: '冰岛语', displayNameIT: 'Islandese', displayNameES: 'islandés', displayNameKO: '아이슬란드어', displayNameID: 'Islan', displayNameVI: 'Iceland', displayNameDE: 'Isländisch', displayNamePT: 'Islandês', displayNameFR: 'Islandais', displayNameTR: 'İzlandaca', displayNameRU: 'исландский', nativeName: 'Íslenska' },
  { languageCode: 'ig', displayNameEN: 'Igbo', displayNameTH: 'อิกโบ', displayNameJA: 'イボ語', displayNameZH: '伊博语', displayNameIT: 'Igbo', displayNameES: 'igbo', displayNameKO: '이그보어', displayNameID: 'Igbo', displayNameVI: 'Igbo', displayNameDE: 'Igbo', displayNamePT: 'Igbo', displayNameFR: 'Igbo', displayNameTR: 'İgbo Dili', displayNameRU: 'игбо', nativeName: 'igbo' },
  { languageCode: 'ga', displayNameEN: 'Irish', displayNameTH: 'ไอร์แลนด์', displayNameJA: 'アイルランド語', displayNameZH: '爱尔兰语', displayNameIT: 'Irlandese', displayNameES: 'irlandés', displayNameKO: '아일랜드어', displayNameID: 'Gaelig', displayNameVI: 'Ireland', displayNameDE: 'Irisch', displayNamePT: 'Irlandês', displayNameFR: 'Irlandais', displayNameTR: 'İrlandaca', displayNameRU: 'ирландский', nativeName: 'Gaeilge' },
  { languageCode: 'it', displayNameEN: 'Italian', displayNameTH: 'อิตาลี', displayNameJA: 'イタリア語', displayNameZH: '意大利语', displayNameIT: 'Italiano', displayNameES: 'italiano', displayNameKO: '이탈리아어', displayNameID: 'Italia', displayNameVI: 'Ý', displayNameDE: 'Italienisch', displayNamePT: 'Italiano', displayNameFR: 'Italien', displayNameTR: 'İtalyanca', displayNameRU: 'итальянский', nativeName: 'italiano' },
  { languageCode: 'kn', displayNameEN: 'Kannada', displayNameTH: 'กันนาดา', displayNameJA: 'カンナダ語', displayNameZH: '卡纳达语', displayNameIT: 'Kannada', displayNameES: 'canarés', displayNameKO: '칸나다어', displayNameID: 'Kannada', displayNameVI: 'Kannada', displayNameDE: 'Kannada', displayNamePT: 'Canarim', displayNameFR: 'Kannada', displayNameTR: 'Kannada', displayNameRU: 'каннада', nativeName: 'ಕನ್ನಡ' },
  { languageCode: 'kk', displayNameEN: 'Kazakh', displayNameTH: 'คาซัค', displayNameJA: 'カザフ語', displayNameZH: '哈萨克语', displayNameIT: 'Kazako', displayNameES: 'kazajo', displayNameKO: '카자흐어', displayNameID: 'Kazak', displayNameVI: 'Kazakh', displayNameDE: 'Kasachisch', displayNamePT: 'Cazaque', displayNameFR: 'Kazakh', displayNameTR: 'Kazakça', displayNameRU: 'казахский', nativeName: 'Қазақ тілі' },
  { languageCode: 'km', displayNameEN: 'Khmer', displayNameTH: 'เขมร', displayNameJA: 'クメール語', displayNameZH: '高棉语', displayNameIT: 'Khmer', displayNameES: 'camboyano', displayNameKO: '크메르어', displayNameID: 'Khmer', displayNameVI: 'Khmer', displayNameDE: 'Khmer', displayNamePT: 'Khmer', displayNameFR: 'Khmer', displayNameTR: 'Kamboçyaca', displayNameRU: 'кхмерский', nativeName: 'ភាសាខ្មែរ' },
  { languageCode: 'rw', displayNameEN: 'Kinyarwanda', displayNameTH: 'คินยารวันดา', displayNameJA: 'キニヤルワンダ語', displayNameZH: '卢旺达语', displayNameIT: 'Kinyarwanda', displayNameES: 'kinyarwanda', displayNameKO: '키냐르완다어', displayNameID: 'Kinyarwanda', displayNameVI: 'Kinyarwanda', displayNameDE: 'Kinyarwanda', displayNamePT: 'Kinyarwanda', displayNameFR: 'Kinyarwanda', displayNameTR: 'Ruandaca', displayNameRU: 'руанда', nativeName: 'Ikinyarwanda' },
  { languageCode: 'ko', displayNameEN: 'Korean', displayNameTH: 'เกาหลี', displayNameJA: '韓国語', displayNameZH: '韩语', displayNameIT: 'Coreano', displayNameES: 'coreano', displayNameKO: '한국어', displayNameID: 'Korea', displayNameVI: 'Hàn', displayNameDE: 'Koreanisch', displayNamePT: 'Coreano', displayNameFR: 'Coréen', displayNameTR: 'Korece', displayNameRU: 'корейский', nativeName: '한국어' },
  { languageCode: 'ku', displayNameEN: 'Kurdish (Kurmanji)', displayNameTH: 'เคิร์ด', displayNameJA: 'クルド語', displayNameZH: '库尔德语', displayNameIT: 'Curdo (kurmanji)', displayNameES: 'kurdo', displayNameKO: '쿠르드어', displayNameID: 'Kurdi', displayNameVI: 'Kurd', displayNameDE: 'Kurdisch (Kurmandschi)', displayNamePT: 'Curdo (curmanji)', displayNameFR: 'Kurde', displayNameTR: 'Kürtçe', displayNameRU: 'курманджи', nativeName: 'Kurdí' },
  { languageCode: 'ky', displayNameEN: 'Kyrgyz', displayNameTH: 'คีร์กิซ', displayNameJA: 'キルギス語', displayNameZH: '吉尔吉斯语', displayNameIT: 'Kirghiso', displayNameES: 'kirguís', displayNameKO: '키르기스어', displayNameID: 'Kirghiz', displayNameVI: 'Kyrgyz', displayNameDE: 'Kirgisisch', displayNamePT: 'Quirguiz', displayNameFR: 'Kirghiz', displayNameTR: 'Kırgızca', displayNameRU: 'киргизский', nativeName: 'قىرعىز (kyrgyz) قىرعىز تىلى (kyrgyz tili)' },
  { languageCode: 'lo', displayNameEN: 'Lao', displayNameTH: 'ลาว', displayNameJA: 'ラオ語', displayNameZH: '老挝语', displayNameIT: 'Lao', displayNameES: 'lao', displayNameKO: '라오어', displayNameID: 'Laos', displayNameVI: 'Lào', displayNameDE: 'Lao', displayNamePT: 'Lao', displayNameFR: 'Laotien', displayNameTR: 'Laoca', displayNameRU: 'лаосский', nativeName: 'ພາສາລາວ' },
  { languageCode: 'la', displayNameEN: 'latin', displayNameTH: 'ละติน', displayNameJA: 'ラテン語', displayNameZH: '拉丁语', displayNameIT: 'Latino', displayNameES: 'latín', displayNameKO: '라틴어', displayNameID: 'Latin', displayNameVI: 'Latinh', displayNameDE: 'Lateinisch', displayNamePT: 'Latino', displayNameFR: 'Latin', displayNameTR: 'Latince', displayNameRU: 'латинский', nativeName: 'Lingua Latina' },
  { languageCode: 'lv', displayNameEN: 'latvian', displayNameTH: 'ลัตเวีย', displayNameJA: 'ラトビア語', displayNameZH: '拉脱维亚语', displayNameIT: 'Lettone', displayNameES: 'letón', displayNameKO: '라트비아어', displayNameID: 'Latvia', displayNameVI: 'Latvia', displayNameDE: 'Lettisch', displayNamePT: 'Letão', displayNameFR: 'Letton', displayNameTR: 'Letonca', displayNameRU: 'латышский', nativeName: 'latviešu valoda' },
  { languageCode: 'lt', displayNameEN: 'lithuanian', displayNameTH: 'ลิทัวเนีย', displayNameJA: 'リトアニア語', displayNameZH: '意大利语', displayNameIT: 'Lituano', displayNameES: 'lituano', displayNameKO: '리투아니아어', displayNameID: 'Lituania', displayNameVI: 'Litva', displayNameDE: 'Litauisch', displayNamePT: 'Lituano', displayNameFR: 'Lituanien', displayNameTR: 'Litvanca', displayNameRU: 'литовский', nativeName: 'lietuvių kalba' },
  { languageCode: 'lb', displayNameEN: 'luxembourgish', displayNameTH: 'ลักเซมเบิร์ก', displayNameJA: 'ルクセンブルク語', displayNameZH: '卢森堡语', displayNameIT: 'Lussemburghese', displayNameES: 'luxemburgués', displayNameKO: '룩셈부르크어', displayNameID: 'Luksemburg', displayNameVI: 'Luxembourg', displayNameDE: 'Luxemburgisch', displayNamePT: 'Luxemburguês', displayNameFR: 'Luxembourgeois', displayNameTR: 'Lüksemburgca', displayNameRU: 'люксембургский', nativeName: 'Lëtzebuergesch' },
  { languageCode: 'mk', displayNameEN: 'Macedonian', displayNameTH: 'มาซีโดเนีย', displayNameJA: 'マケドニア語', displayNameZH: '马其顿语', displayNameIT: 'Macedone', displayNameES: 'macedonio', displayNameKO: '마케도니아어', displayNameID: 'Makedonia', displayNameVI: 'Macedonia', displayNameDE: 'Mazedonisch', displayNamePT: 'Macedônio', displayNameFR: 'Macédonien', displayNameTR: 'Makedonca', displayNameRU: 'македонский', nativeName: 'македонски (Makedonski) македонски јазик (makedonski jazik)' },
  { languageCode: 'mg', displayNameEN: 'Malagasy', displayNameTH: 'มาลากาซี', displayNameJA: 'マラガシ語', displayNameZH: '马尔加什语', displayNameIT: 'Malgascio', displayNameES: 'malgache', displayNameKO: '말라가시어', displayNameID: 'Malagasi', displayNameVI: 'Malagasy', displayNameDE: 'Malagasy', displayNamePT: 'Malgaxe', displayNameFR: 'Malgache', displayNameTR: 'Madagaskar Dili', displayNameRU: 'малагасийский', nativeName: 'Fiteny Malagasy' },
  { languageCode: 'ml', displayNameEN: 'Malayalam', displayNameTH: 'มาลายาลัม', displayNameJA: 'マラヤーラム語', displayNameZH: '马拉雅拉姆语', displayNameIT: 'Malayalam', displayNameES: 'malayalam', displayNameKO: '말라얄람어', displayNameID: 'Malayalam', displayNameVI: 'Malayalam', displayNameDE: 'Malayalam', displayNamePT: 'Malaiala', displayNameFR: 'Malayalam', displayNameTR: 'Malayalam', displayNameRU: 'малаялам', nativeName: 'മലയാളം (malayāḷam)' },
  { languageCode: 'mt', displayNameEN: 'Maltese', displayNameTH: 'มัลทีส', displayNameJA: 'マルタ語', displayNameZH: '马耳他语', displayNameIT: 'Maltese', displayNameES: 'maltés', displayNameKO: '몰타어', displayNameID: 'Malta', displayNameVI: 'Malta', displayNameDE: 'Maltesisch', displayNamePT: 'Maltês', displayNameFR: 'Maltais', displayNameTR: 'Malta Dili', displayNameRU: 'мальтийский', nativeName: 'Malti' },
  { languageCode: 'mi', displayNameEN: 'Maori', displayNameTH: 'เมารี', displayNameJA: 'マオリ語', displayNameZH: '毛利语', displayNameIT: 'Maori', displayNameES: 'maorí', displayNameKO: '마오리어', displayNameID: 'Maori', displayNameVI: 'Maori', displayNameDE: 'Maori', displayNamePT: 'Maori', displayNameFR: 'Maori', displayNameTR: 'Maori Dili', displayNameRU: 'маори', nativeName: 'te Reo Māori' },
  { languageCode: 'mr', displayNameEN: 'Marathi', displayNameTH: 'มาราฐี', displayNameJA: 'マラーティー語', displayNameZH: '马拉地语', displayNameIT: 'Marathi', displayNameES: 'maratí', displayNameKO: '마라티어', displayNameID: 'Marathi', displayNameVI: 'Marathi', displayNameDE: 'Marathi', displayNamePT: 'Marati', displayNameFR: 'Marathi', displayNameTR: 'Marathi', displayNameRU: 'маратхи', nativeName: 'मराठी (marāṭhī)' },
  { languageCode: 'mn', displayNameEN: 'Mongolian', displayNameTH: 'มองโกเลีย', displayNameJA: 'モンゴル語', displayNameZH: '蒙古语', displayNameIT: 'Mongolo', displayNameES: 'mongol', displayNameKO: '몽골어', displayNameID: 'Mongol', displayNameVI: 'Mông Cổ', displayNameDE: 'Mongolisch', displayNamePT: 'Mongol', displayNameFR: 'Mongol', displayNameTR: 'Moğolca', displayNameRU: 'монгольский', nativeName: 'монгол (mongol) монгол хэл (mongol hêl)' },
  { languageCode: 'my', displayNameEN: 'Myanmar (Burmese)', displayNameTH: 'เมียนมา (พม่า)', displayNameJA: 'ミャンマー語', displayNameZH: '缅甸语', displayNameIT: 'Birmano', displayNameES: 'birmano', displayNameKO: '미얀마어 (버마어)', displayNameID: 'Burma', displayNameVI: 'Myanmar', displayNameDE: 'Birmanisch', displayNamePT: 'Mianmar (birmanês)', displayNameFR: 'Birman', displayNameTR: 'Burmaca', displayNameRU: 'бирманский', nativeName: 'ဗမာစကား (bama saka)' },
  { languageCode: 'ne', displayNameEN: 'Nepali', displayNameTH: 'เนปาล', displayNameJA: 'ネパール語', displayNameZH: '尼泊尔语', displayNameIT: 'Nepalese', displayNameES: 'nepalí', displayNameKO: '네팔어', displayNameID: 'Nepal', displayNameVI: 'Nepal', displayNameDE: 'Nepalesisch', displayNamePT: 'Nepalês', displayNameFR: 'Népalais', displayNameTR: 'Nepalce', displayNameRU: 'непальский', nativeName: 'नेपाली (nēpālī)' },
  { languageCode: 'no', displayNameEN: 'Norwegian', displayNameTH: 'นอร์เวย์', displayNameJA: 'ノルウェー語', displayNameZH: '挪威语', displayNameIT: 'Norvegese', displayNameES: 'noruego', displayNameKO: '노르웨이어', displayNameID: 'Norsk', displayNameVI: 'Na Uy', displayNameDE: 'Norwegisch', displayNamePT: 'Norueguês', displayNameFR: 'Norvégien', displayNameTR: 'Norveççe', displayNameRU: 'норвежский', nativeName: 'Norsk' },
  { languageCode: 'or', displayNameEN: 'Odia (Oriya)', displayNameTH: 'โอเดีย (โอริยา)', displayNameJA: 'オリヤ語', displayNameZH: '奥里亚语(奥里亚文)', displayNameIT: 'Odia (oriya)', displayNameES: 'oriya', displayNameKO: '오리야어', displayNameID: 'Odia (Oriya)', displayNameVI: 'Odia (Oriya)', displayNameDE: 'Odia (Oriya)', displayNamePT: 'Odia (Oriya)', displayNameFR: 'Odia (oriya)', displayNameTR: 'Odiya (Oriya)', displayNameRU: 'ория', nativeName: 'ଓଡ଼ିଆ (ōṛiyā)' },
  { languageCode: 'ps', displayNameEN: 'Pashto', displayNameTH: 'พาชตู', displayNameJA: 'パシュト語', displayNameZH: '普什图语', displayNameIT: 'Pashto', displayNameES: 'pastún', displayNameKO: '파슈토어', displayNameID: 'Pashto', displayNameVI: 'Pashto', displayNameDE: 'Paschtu', displayNamePT: 'Pashto', displayNameFR: 'Pachtô', displayNameTR: 'Peştuca', displayNameRU: 'пушту', nativeName: '(paṧto) پښتو' },
  { languageCode: 'fa', displayNameEN: 'Persian', displayNameTH: 'เปอร์เซีย', displayNameJA: 'ペルシャ語', displayNameZH: '波斯语', displayNameIT: 'Persiano', displayNameES: 'persa', displayNameKO: '페르시아어', displayNameID: 'Farsi', displayNameVI: 'Ba Tư', displayNameDE: 'Persisch', displayNamePT: 'Persa', displayNameFR: 'Persan', displayNameTR: 'Farsça', displayNameRU: 'персидский', nativeName: '(fārsī) فارسى' },
  { languageCode: 'pl', displayNameEN: 'Polish', displayNameTH: 'โปแลนด์', displayNameJA: 'ポーランド語', displayNameZH: '波兰语', displayNameIT: 'Polacco', displayNameES: 'polaco', displayNameKO: '폴란드어', displayNameID: 'Polandia', displayNameVI: 'Ba Lan', displayNameDE: 'Polnisch', displayNamePT: 'Polonês', displayNameFR: 'Polonais', displayNameTR: 'Lehçe', displayNameRU: 'польский', nativeName: 'polski / język polski / polszczyzna' },
  { languageCode: 'pt', displayNameEN: 'Portuguese', displayNameTH: 'โปรตุเกส', displayNameJA: 'ポルトガル語', displayNameZH: '葡萄牙语', displayNameIT: 'Portoghese', displayNameES: 'portugués', displayNameKO: '포르투갈어', displayNameID: 'Portugis', displayNameVI: 'Bồ Đào Nha', displayNameDE: 'Portugiesisch', displayNamePT: 'Português', displayNameFR: 'Portugais', displayNameTR: 'Portekizce', displayNameRU: 'португальский', nativeName: 'Português' },
  { languageCode: 'pa', displayNameEN: 'Punjabi', displayNameTH: 'ปัญจาป', displayNameJA: 'パンジャブ語', displayNameZH: '旁遮普语', displayNameIT: 'Punjabi', displayNameES: 'panyabí', displayNameKO: '펀자브어', displayNameID: 'Punjabi', displayNameVI: 'Punjab', displayNameDE: 'Punjabi', displayNamePT: 'Punjabi', displayNameFR: 'Panjabi', displayNameTR: 'Pencap Dili', displayNameRU: 'панджаби', nativeName: 'ਪੰਜਾਬੀ / ﺏﺎﺠﻨﭘ (panjābi)' },
  { languageCode: 'ro', displayNameEN: 'Romanian', displayNameTH: 'โรมาเนีย', displayNameJA: 'ルーマニア語', displayNameZH: '罗马尼亚语', displayNameIT: 'Rumeno', displayNameES: 'rumano', displayNameKO: '루마니아어', displayNameID: 'Rumania', displayNameVI: 'Rumani', displayNameDE: 'Rumänisch', displayNamePT: 'Romeno', displayNameFR: 'Roumain', displayNameTR: 'Romence', displayNameRU: 'румынский', nativeName: 'limba română / român' },
  { languageCode: 'ru', displayNameEN: 'Russian', displayNameTH: 'รัสเซีย', displayNameJA: 'ロシア語', displayNameZH: '俄语', displayNameIT: 'Russo', displayNameES: 'ruso', displayNameKO: '러시아어', displayNameID: 'Rusia', displayNameVI: 'Nga', displayNameDE: 'Russisch', displayNamePT: 'Russo', displayNameFR: 'Russe', displayNameTR: 'Rusça', displayNameRU: 'русский', nativeName: 'Русский язык (Russkij jazyk)' },
  { languageCode: 'sm', displayNameEN: 'Samoan', displayNameTH: 'ซามัว', displayNameJA: 'サモア語', displayNameZH: '萨摩亚语', displayNameIT: 'Samoano', displayNameES: 'samoano', displayNameKO: '사모아어', displayNameID: 'Samoa', displayNameVI: 'Samoa', displayNameDE: 'Samoanisch', displayNamePT: 'Samoano', displayNameFR: 'Samoan', displayNameTR: 'Samoaca', displayNameRU: 'самоанский', nativeName: 'Gagana Samoa' },
  { languageCode: 'gd', displayNameEN: 'Scots Gaelic', displayNameTH: 'เกลิกสกอต', displayNameJA: 'スコットランド ゲール語', displayNameZH: '苏格兰盖尔语', displayNameIT: 'Gaelico scozzese', displayNameES: 'gaélico escocés', displayNameKO: '스코틀랜드 게일어', displayNameID: 'Gaelik Skotlandia', displayNameVI: 'Gael Scotland', displayNameDE: 'Schottisch-Gälisch', displayNamePT: 'Gaélico escocês', displayNameFR: 'Gaélique (Écosse)', displayNameTR: 'Kuzey İskoç Dili', displayNameRU: 'шотландский (гэльский)', nativeName: 'Scoats leid / Lallans' },
  { languageCode: 'sr', displayNameEN: 'Serbian', displayNameTH: 'เซอร์เบียน', displayNameJA: 'セルビア語', displayNameZH: '塞尔维亚语', displayNameIT: 'Serbo', displayNameES: 'serbio', displayNameKO: '세르비아어', displayNameID: 'Serb', displayNameVI: 'Serbia', displayNameDE: 'Serbisch', displayNamePT: 'Sérvio', displayNameFR: 'Serbe', displayNameTR: 'Sırpça', displayNameRU: 'сербский', nativeName: 'српски (srpski) српски језик (srpski jezik)' },
  { languageCode: 'st', displayNameEN: 'Sesotho', displayNameTH: 'เซโซโท', displayNameJA: 'ソト語', displayNameZH: '塞索托语', displayNameIT: 'Sesotho', displayNameES: 'sesoto', displayNameKO: '세소토어', displayNameID: 'Sesotho', displayNameVI: 'Sesotho', displayNameDE: 'Sesotho', displayNamePT: 'Sesotho', displayNameFR: 'Sesotho', displayNameTR: 'Sesotho Dili', displayNameRU: 'сесото', nativeName: 'ᑌᓀ ᒐ (dene tha)' },
  { languageCode: 'sn', displayNameEN: 'Shona', displayNameTH: 'โชนา', displayNameJA: 'ショナ語', displayNameZH: '修纳语', displayNameIT: 'Shona', displayNameES: 'shona', displayNameKO: '쇼나어', displayNameID: 'Shona', displayNameVI: 'Shona', displayNameDE: 'Shona', displayNamePT: 'Shona', displayNameFR: 'Shona', displayNameTR: 'Shona', displayNameRU: 'шона', nativeName: 'Shona' },
  { languageCode: 'sd', displayNameEN: 'Sindhi', displayNameTH: 'สินธี', displayNameJA: 'シンド語', displayNameZH: '信德语', displayNameIT: 'Sindhi', displayNameES: 'sindhi', displayNameKO: '신디어', displayNameID: 'Sindhi', displayNameVI: 'Sindhi', displayNameDE: 'Sindhi', displayNamePT: 'Sindi', displayNameFR: 'Sindhî', displayNameTR: 'Sint', displayNameRU: 'синдхи', nativeName: 'سنڌي' },
  { languageCode: 'si', displayNameEN: 'Sinhala', displayNameTH: 'สิงหล', displayNameJA: 'シンハラ語', displayNameZH: '僧伽罗语', displayNameIT: 'Singalese', displayNameES: 'cingalés', displayNameKO: '신할라어', displayNameID: 'Sinhala', displayNameVI: 'Sinhala', displayNameDE: 'Singhalesisch', displayNamePT: 'Cingalês', displayNameFR: 'Cingalais', displayNameTR: 'Seylanca', displayNameRU: 'сингальский', nativeName: 'සිංහල' },
  { languageCode: 'sk', displayNameEN: 'Slovak', displayNameTH: 'สโลวัก', displayNameJA: 'スロバキア語', displayNameZH: '斯洛伐克语', displayNameIT: 'Slovacco', displayNameES: 'eslovaco', displayNameKO: '슬로바키아어', displayNameID: 'Slovakia', displayNameVI: 'Slovak', displayNameDE: 'Slowakisch', displayNamePT: 'Eslovaco', displayNameFR: 'Slovaque', displayNameTR: 'Slovakça', displayNameRU: 'словацкий', nativeName: 'slovenčina' },
  { languageCode: 'sl', displayNameEN: 'Slovenian', displayNameTH: 'สโลวีเนีย', displayNameJA: 'スロベニア語', displayNameZH: '斯洛文尼亚语', displayNameIT: 'Sloveno', displayNameES: 'esloveno', displayNameKO: '슬로베니아어', displayNameID: 'Slovenia', displayNameVI: 'Slovenia', displayNameDE: 'Slowenisch', displayNamePT: 'Esloveno', displayNameFR: 'Slovène', displayNameTR: 'Slovence', displayNameRU: 'словенский', nativeName: 'slovenščina' },
  { languageCode: 'so', displayNameEN: 'Somali', displayNameTH: 'โซมาลี', displayNameJA: 'ソマリ語', displayNameZH: '索马里语', displayNameIT: 'Somalo', displayNameES: 'somalí', displayNameKO: '소말리아어', displayNameID: 'Somali', displayNameVI: 'Somali', displayNameDE: 'Somali', displayNamePT: 'Somali', displayNameFR: 'Somali', displayNameTR: 'Somalice', displayNameRU: 'сомалийский', nativeName: 'af Soomaali' },
  { languageCode: 'es', displayNameEN: 'Spanish', displayNameTH: 'สเปน', displayNameJA: 'スペイン語', displayNameZH: '西班牙语', displayNameIT: 'Spagnolo', displayNameES: 'español', displayNameKO: '스페인어', displayNameID: 'Spanyol', displayNameVI: 'Tây Ban Nha', displayNameDE: 'Spanisch', displayNamePT: 'Espanhol', displayNameFR: 'Espagnol', displayNameTR: 'İspanyolca', displayNameRU: 'испанский', nativeName: 'español' },
  { languageCode: 'sw', displayNameEN: 'Swahili', displayNameTH: 'สวาฮิลี', displayNameJA: 'スワヒリ語', displayNameZH: '斯瓦希里语', displayNameIT: 'Swahili', displayNameES: 'suajili', displayNameKO: '스와힐리어', displayNameID: 'Swahili', displayNameVI: 'Swahili', displayNameDE: 'Suaheli', displayNamePT: 'Suaíli', displayNameFR: 'Swahili', displayNameTR: 'Svahili Dili', displayNameRU: 'суахили', nativeName: 'Kiswahili' },
  { languageCode: 'sv', displayNameEN: 'Swedish', displayNameTH: 'สวีเดน', displayNameJA: 'スウェーデン語', displayNameZH: '瑞典语', displayNameIT: 'Svedese', displayNameES: 'sueco', displayNameKO: '스웨덴어', displayNameID: 'Swensk', displayNameVI: 'Thụy Điển', displayNameDE: 'Schwedisch', displayNamePT: 'Sueco', displayNameFR: 'Suédois', displayNameTR: 'İsveççe', displayNameRU: 'шведский', nativeName: 'Svenska' },
  { languageCode: 'tg', displayNameEN: 'Tajik', displayNameTH: 'ทาจิก', displayNameJA: 'タジク語', displayNameZH: '塔吉克语', displayNameIT: 'Tagiko', displayNameES: 'tayiko', displayNameKO: '타지크어', displayNameID: 'Tajik', displayNameVI: 'Tajik', displayNameDE: 'Tadschikisch', displayNamePT: 'Tadjique', displayNameFR: 'Tadjik', displayNameTR: 'Tacikce', displayNameRU: 'таджикский', nativeName: 'тоҷики' },
  { languageCode: 'ta', displayNameEN: 'Tamil', displayNameTH: 'ทมิฬ', displayNameJA: 'タミル語', displayNameZH: '泰米尔语', displayNameIT: 'Tamil', displayNameES: 'tamil', displayNameKO: '타밀어', displayNameID: 'Tamil', displayNameVI: 'Tamil', displayNameDE: 'Tamil', displayNamePT: 'Tâmil', displayNameFR: 'Tamoul', displayNameTR: 'Tamil', displayNameRU: 'тамильский', nativeName: 'தமிழ்' },
  { languageCode: 'tt', displayNameEN: 'Tatar', displayNameTH: 'ทาทาร์', displayNameJA: 'タタール語', displayNameZH: '鞑靼语', displayNameIT: 'Tataro', displayNameES: 'tártaro', displayNameKO: '타타르어', displayNameID: 'Tatar', displayNameVI: 'Tatar', displayNameDE: 'Tatarisch', displayNamePT: 'Tártaro', displayNameFR: 'Tatar', displayNameTR: 'Tatarca', displayNameRU: 'татарский', nativeName: 'татарча' },
  { languageCode: 'te', displayNameEN: 'Telugu', displayNameTH: 'เตลูกู', displayNameJA: 'テルグ語', displayNameZH: '泰卢固语', displayNameIT: 'Telugu', displayNameES: 'telugu', displayNameKO: '텔루구어', displayNameID: 'Telugu', displayNameVI: 'Telugu', displayNameDE: 'Telugu', displayNamePT: 'Telugu', displayNameFR: 'Telugu', displayNameTR: 'Telugu Dili', displayNameRU: 'телугу', nativeName: 'తెలుగు' },
  { languageCode: 'tr', displayNameEN: 'Turkish', displayNameTH: 'ตุรกี', displayNameJA: 'トルコ語', displayNameZH: '土耳其语', displayNameIT: 'Turco', displayNameES: 'turco', displayNameKO: '터키어', displayNameID: 'Turki', displayNameVI: 'Thổ Nhĩ Kỳ', displayNameDE: 'Türkisch', displayNamePT: 'Turco', displayNameFR: 'Turc', displayNameTR: 'Türkçe', displayNameRU: 'турецкий', nativeName: 'Türkçe' },
  { languageCode: 'uk', displayNameEN: 'Ukrainian', displayNameTH: 'ยูเครน', displayNameJA: 'ウクライナ語', displayNameZH: '乌克兰语', displayNameIT: 'Ucraino', displayNameES: 'ucraniano', displayNameKO: '우크라이나어', displayNameID: 'Ukraina', displayNameVI: 'Ukraina', displayNameDE: 'Ukrainisch', displayNamePT: 'Ucraniano', displayNameFR: 'Ukrainien', displayNameTR: 'Ukraynaca', displayNameRU: 'украинский', nativeName: 'Українська' },
  { languageCode: 'ur', displayNameEN: 'Urdu', displayNameTH: 'อูรดู', displayNameJA: 'ウルドゥ語', displayNameZH: '乌尔都语', displayNameIT: 'Urdu', displayNameES: 'urdu', displayNameKO: '우르두어', displayNameID: 'Urdu', displayNameVI: 'Urdu', displayNameDE: 'Urdu', displayNamePT: 'Urdu', displayNameFR: 'Urdu', displayNameTR: 'Urduca', displayNameRU: 'урду', nativeName: '(urdū) اردو' },
  { languageCode: 'ug', displayNameEN: 'Uyghur', displayNameTH: 'อุยกูร์', displayNameJA: 'ウイグル語', displayNameZH: '维吾尔语', displayNameIT: 'Uiguro', displayNameES: 'uigur', displayNameKO: '위구르어', displayNameID: 'Uyghur', displayNameVI: 'Uyghur', displayNameDE: 'Uigurisch', displayNamePT: 'Uigur', displayNameFR: 'Ouïgour', displayNameTR: 'Uygurca', displayNameRU: 'уйгурский', nativeName: 'Уйғур' },
  { languageCode: 'uz', displayNameEN: 'Uzbek', displayNameTH: 'อุสเบกิสถาน', displayNameJA: 'ウズベク語', displayNameZH: '乌兹别克语', displayNameIT: 'Uzbeco', displayNameES: 'uzbeco', displayNameKO: '우즈베크어', displayNameID: 'Uzbek', displayNameVI: 'Uzbek', displayNameDE: 'Usbekisch', displayNamePT: 'Uzbeque', displayNameFR: 'Ouzbek', displayNameTR: 'Özbekçe', displayNameRU: 'узбекский', nativeName: 'ўзбек тили' },
  { languageCode: 'cy', displayNameEN: 'Welsh', displayNameTH: 'เวลส์', displayNameJA: 'ウェールズ語', displayNameZH: '威尔士语', displayNameIT: 'Gallese', displayNameES: 'galés', displayNameKO: '웨일즈어', displayNameID: 'Wales', displayNameVI: 'Xứ Wales', displayNameDE: 'Walisisch', displayNamePT: 'Galês', displayNameFR: 'Gallois', displayNameTR: 'Galce', displayNameRU: 'валлийский', nativeName: 'Y Gymraeg' },
  { languageCode: 'xh', displayNameEN: 'Xhosa', displayNameTH: 'โคซา', displayNameJA: 'コーサ語', displayNameZH: '南非科萨语', displayNameIT: 'Xhosa', displayNameES: 'xhosa', displayNameKO: '코사어', displayNameID: 'Xhosa', displayNameVI: 'Bantu', displayNameDE: 'Xhosa', displayNamePT: 'Xhosa', displayNameFR: 'Xhosa', displayNameTR: 'Hosa', displayNameRU: 'кхоса', nativeName: 'isiXhosa' },
  { languageCode: 'yi', displayNameEN: 'Yiddish', displayNameTH: 'ยิดดิช', displayNameJA: 'イディッシュ語', displayNameZH: '意第绪语', displayNameIT: 'Yiddish', displayNameES: 'yidis', displayNameKO: '이디시어', displayNameID: 'Yiddi', displayNameVI: 'Yiddish', displayNameDE: 'Jiddisch', displayNamePT: 'Iídiche', displayNameFR: 'Yiddish', displayNameTR: 'Yidce', displayNameRU: 'идиш', nativeName: '(Yidish) ײִדיש' },
  { languageCode: 'yo', displayNameEN: 'Yoruba', displayNameTH: 'โยรูบา', displayNameJA: 'ヨルバ語', displayNameZH: '约鲁巴语', displayNameIT: 'Yoruba', displayNameES: 'yoruba', displayNameKO: '요루바어', displayNameID: 'Yoruba', displayNameVI: 'Yoruba', displayNameDE: 'Yoruba', displayNamePT: 'Ioruba', displayNameFR: 'Yorouba', displayNameTR: 'Yoruba', displayNameRU: 'йоруба', nativeName: 'Yorùbá' },
  { languageCode: 'zu', displayNameEN: 'Zulu', displayNameTH: 'ซูลู', displayNameJA: 'ズールー語', displayNameZH: '南非祖鲁语', displayNameIT: 'Zulu', displayNameES: 'zulú', displayNameKO: '줄루어', displayNameID: 'Zulu', displayNameVI: 'Zulu', displayNameDE: 'Zulu', displayNamePT: 'Zulu', displayNameFR: 'Zoulou', displayNameTR: 'Zulu', displayNameRU: 'зулу', nativeName: 'isiZulu' }

  // Translation API does not support Turkmen. 
  //{ languageCode: 'tk', displayNameEN: 'Turkmen', displayNameTH: 'เติร์กเมน', displayNameJA: 'トルクメン語', displayNameZH: '土库曼语', displayNameIT: 'Turkmeno', displayNameES: 'turkmeno', displayNameKO:'투르크멘어', nativeName: 'түркmенче' },
];

@Injectable({
  providedIn: 'root'
})
export class LanguageService {

  constructor() { }

  getLanguage(code) {
    return this.getSupportedLanguages(null).find(l => l.languageCode === code);
  }

  getSupportedLanguages(code) {
    let selected = supportedLanguages.find(l => l.languageCode === code);

    // update the sortOrder of selected language so it is at top of the list
    if (selected) selected.sortOrder = 6;

    return supportedLanguages;
  }
}
